name: ci-nodejs-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node ${{matrix.node}} test
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
          cache-dependency-path: "**/packages/functional/package-lock.json"
      - run: npm install
      - run: npm run 'set:server'
